apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  labels:
    app: web-server
spec:
  selector:
    app: web-server
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
