apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/forgejo-forgejo: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: forgejo
            - name: POSTGRES_PASSWORD
              value: forgejo
            - name: POSTGRES_USER
              value: forgejo
          image: postgres:14
          name: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-claim0
          resources:
            limits:
              cpu: "1000m"
              memory: 2048Mi
            requests:
              cpu: "500m"
              memory: 1024Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Always
      volumes:
        - name: db-claim0
          persistentVolumeClaim:
            claimName: db-claim0
