apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "22"
      port: 22
      targetPort: 22
  selector:
    io.kompose.service: server
