apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: server-claim1
  name: server-claim1
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1024Mi
